# _config.yml
title: "SADAKA Charity Site"
description: "Charity / Non-profit responsive Bootstrap Jekyll template."

#baseurl: ""         # Se hai sito in una sottocartella, impostala qui (es. /mysite)
#url: "http://yourdomain.com"

baseurl: "sadaka-jekyll"         # Se hai sito in una sottocartella, impostala qui (es. /mysite)
url: "https://docemus.github.io"

